import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GraphQLClient, gql } from "graphql-request"
import BlogCard from '@/components/BlogCard'

const graphcms = new GraphQLClient("https://api-ap-northeast-1.hygraph.com/v2/clolhsiu28dsi01t7di3oeetd/master");

//全てのブログ情報を取得するAPIを叩く
const QUERY = gql`
  {
    posts{
      id
      title
      datePublished
      slug
      content{
        html
      }
      author{
        name
        avatar{
          url
        }
      }
      photo{
        createdBy{
          id
        }
        url
      }
    }
  }
`;

//getStaticPropsでSSGを実装
export async function getStaticProps() {
  //APIを取得
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Atsumi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          <h2>NextjsとGraphQLブログ</h2>
        </div>
        <div className={styles.gridWrapper}>
          {posts.map((post) => (
            <BlogCard 
              photo={post.photo} 
              title={post.title} 
              author={post.author} 
              date={post.datePublished}
              slug={post.slug}
              key={post.id}
            />
            ))}
        </div>
      </main>
    </>
  );
}
